name: macOS
on:
  push:
    branches-ignore:
      - debian
      - khronos-registry
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        build-opts:
          - ''
          - '-Dglx=no'
          - '-Degl=yes'
          - '-Dx11=false'
      # Prevent the entire matrix from failing if one configuration fails
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('.github/workflows/macos.yml') }}
      - name: Install dependencies and build
        run: |
          # Check if ninja is installed, install only if not present
          if ! command -v ninja &> /dev/null; then
            brew install ninja
          fi
          python -m pip install --upgrade pip
          pip3 install meson
          mkdir -p meson-logs
          /bin/sh -c "CC=clang .github/scripts/epoxy-ci-osx.sh ${{ matrix.build-opts }}" || true
          # Ensure there's something in the logs directory for artifact upload
          touch meson-logs/build.log
          
          # Debug: Find where build artifacts are located
          echo "==== Listing potential build directories ===="
          find . -type d -name "build*" | sort
          find . -name "*.dylib" | sort
          find . -name "*.a" | sort
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-${{ matrix.build-opts || 'default' }}
          path: |
            meson-logs/
          retention-days: 7
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: libepoxy-build-${{ matrix.build-opts || 'default' }}
          path: |
            **/*.dylib
            **/*.a
            **/build*/
          retention-days: 30
