name: macOS
on:
  push:
    branches-ignore:
      - debian
      - khronos-registry
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        build-opts:
          - ''
          - '-Dglx=no'
          - '-Degl=yes'
          - '-Dx11=false'
      # Prevent the entire matrix from failing if one configuration fails
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('.github/workflows/macos.yml') }}
      - name: Install dependencies and build
        run: |
          # Check if ninja is installed, install only if not present
          if ! command -v ninja &> /dev/null; then
            brew install ninja
          fi
          python -m pip install --upgrade pip
          pip3 install meson
          
          # Create directory for build logs
          mkdir -p meson-logs
          
          # Build the project with specified options
          BUILD_DIR=$(mktemp -d -t build_XXXXXX)
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
          
          /bin/sh -c "CC=clang BUILDDIR=$BUILD_DIR .github/scripts/epoxy-ci-osx.sh ${{ matrix.build-opts }}" || true
          
          # Ensure there's something in the logs directory for artifact upload
          if [ -d "$BUILD_DIR/meson-logs" ]; then
            cp -R "$BUILD_DIR/meson-logs/"* meson-logs/ || true
          fi
          touch meson-logs/build.log
          
          # Debug output
          echo "==== Build Directory ====="
          echo $BUILD_DIR
          echo "==== Listing contents of build directory ===="
          ls -la $BUILD_DIR
          echo "==== Listing dylib files ===="
          find $BUILD_DIR -name "*.dylib" | sort

          # Create a directory for collecting artifacts in the workspace
          WORKSPACE="$GITHUB_WORKSPACE"
          mkdir -p "$WORKSPACE/artifacts"
          
          # Copy libraries
          find $BUILD_DIR -name "*.dylib" -exec cp {} "$WORKSPACE/artifacts/" \;
          
          # Copy test files (if they exist)
          mkdir -p "$WORKSPACE/artifacts/test"
          if [ -d "$BUILD_DIR/test" ]; then
            cp -R $BUILD_DIR/test/* "$WORKSPACE/artifacts/test/" || true
          fi
          
          # Copy header files (if they exist)
          mkdir -p "$WORKSPACE/artifacts/include"
          if [ -d "$BUILD_DIR/include" ]; then
            cp -R $BUILD_DIR/include/* "$WORKSPACE/artifacts/include/" || true
          fi
          
          # List the contents of the artifacts directory to verify
          echo "==== Artifacts Directory Contents ===="
          ls -la "$WORKSPACE/artifacts"
      
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-${{ matrix.build-opts || 'default' }}
          path: meson-logs/
          retention-days: 7
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: libepoxy-build-${{ matrix.build-opts || 'default' }}
          path: artifacts/
          retention-days: 30
