name: macOS
on:
  push:
    branches-ignore:
      - debian
      - khronos-registry
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        build-opts:
          - ''
          - '-Dglx=no'
          - '-Degl=yes'
          - '-Dx11=false'
      # Prevent the entire matrix from failing if one configuration fails
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('.github/workflows/macos.yml') }}
      - name: Install dependencies and build
        run: |
          # Check if ninja is installed, install only if not present
          if ! command -v ninja &> /dev/null; then
            brew install ninja
          fi
          python -m pip install --upgrade pip
          pip3 install meson
          mkdir -p meson-logs
          
          # Run the build script
          /bin/sh -c "CC=clang .github/scripts/epoxy-ci-osx.sh ${{ matrix.build-opts }}" || true
          
          # Ensure there's something in the logs directory for artifact upload
          touch meson-logs/build.log
          
          # Find the build directory that was created
          BUILD_DIR=$(find /var/folders -type d -name "build_*" -mmin -5 | head -1)
          echo "Found build directory: $BUILD_DIR"
          
          # Get just the directory name (not the full path)
          BUILD_NAME=$(basename "$BUILD_DIR")
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          
          # Debug: List what's in the build directory
          echo "==== Contents of $BUILD_DIR ===="
          ls -la "$BUILD_DIR"
          echo "==== Libraries in $BUILD_DIR ===="
          find "$BUILD_DIR" -name "*.dylib" | sort
          
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-${{ matrix.build-opts || 'default' }}
          path: |
            meson-logs/
          retention-days: 7
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: libepoxy-build-${{ matrix.build-opts || 'default' }}
          path: |
            # Only include specific files from the build directory
            /var/folders/**/${{ env.BUILD_NAME }}/src/*.dylib
            /var/folders/**/${{ env.BUILD_NAME }}/include/**/*.h
            /var/folders/**/${{ env.BUILD_NAME }}/test/*
          retention-days: 30
